apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: application-alerts
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
  - name: application
    rules:
    - alert: HighErrorRate
      expr: |
        rate(http_requests_total{status=~"5.*"}[5m]) > 0.1
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: High error rate detected
        description: "Error rate is {{ $value }} for the last 5 minutes"

    - alert: SlowResponses
      expr: |
        rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m]) > 1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: Slow response times detected
        description: "Average response time is {{ $value }}s for the last 5 minutes"

    - alert: HighMemoryUsage
      expr: |
        container_memory_usage_bytes{namespace="backend"} > 1.5e9
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High memory usage detected
        description: "Pod {{ $labels.pod }} is using {{ $value }} bytes of memory"

  - name: system
    rules:
    - alert: NodeHighCPU
      expr: |
        100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High CPU usage on node
        description: "Node {{ $labels.instance }} CPU usage is {{ $value }}%"

    - alert: NodeHighMemory
      expr: |
        (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High memory usage on node
        description: "Node {{ $labels.instance }} memory usage is {{ $value }}%"

    - alert: NodeLowDisk
      expr: |
        (node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"}) / node_filesystem_size_bytes{mountpoint="/"} * 100 > 85
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: Low disk space
        description: "Node {{ $labels.instance }} disk usage is {{ $value }}%" 