services:
  traefik:
    image: traefik:v2.9
    command:
      - "--api.insecure=true" # OK for local dev
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080" # Traefik dashboard for local debugging
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - backend

  go-server:
    build:
      context: ../go-server
      dockerfile: Dockerfile
    expose:
      - "9000"
    volumes:
      - ../go-server/pb_data:/app/pb_data
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.go-server.rule=Host(`localhost`) && !PathPrefix(`/api/import-trades`)"
      - "traefik.http.routers.go-server.entrypoints=web"
      - "traefik.http.services.go-server.loadbalancer.server.port=9000"

  helper-server:
    build:
      context: ../helper-server
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      - MAIN_SERVER_URL=http://go-server:9000
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.helper-server.rule=Host(`localhost`) && PathPrefix(`/api/import-trades`)"
      - "traefik.http.routers.helper-server.entrypoints=web"
      - "traefik.http.services.helper-server.loadbalancer.server.port=8080"

networks:
  backend:
    driver: bridge
