apiVersion: v1
kind: ConfigMap
metadata:
  name: go-server-config
  namespace: backend
data:
  SERVER_PORT: "9000"
  LOG_LEVEL: "info"
  ENVIRONMENT: "production"
  MAX_REQUEST_SIZE: "50mb"
  REQUEST_TIMEOUT: "30s"
  ALLOWED_ORIGINS: "https://api.yourdomain.com"
  app-config.yaml: |
    logging:
      format: json
      level: info
    metrics:
      enabled: true
      path: /metrics
    health:
      enabled: true
      path: /health
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: helper-server-config
  namespace: backend
data:
  PORT: "8080"
  LOG_LEVEL: "info"
  ENVIRONMENT: "production"
  MAX_IMPORT_SIZE: "10mb"
  IMPORT_TIMEOUT: "5m"
  ENABLE_VALIDATION: "true"
  ENABLE_PREPROCESSING: "true" 