apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: backend
type: Opaque
stringData:
  API_KEY: "${API_KEY}"
  ADMIN_TOKEN: "${ADMIN_TOKEN}"
  ENCRYPTION_KEY: "${ENCRYPTION_KEY}"
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
  namespace: backend
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "your-registry": {
          "username": "${REGISTRY_USERNAME}",
          "password": "${REGISTRY_PASSWORD}",
          "email": "${REGISTRY_EMAIL}",
          "auth": "${REGISTRY_AUTH}"
        }
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: backend
type: kubernetes.io/tls
stringData:
  tls.crt: "${TLS_CERT}"
  tls.key: "${TLS_KEY}" 